### PR TITLE
util: added workbegin and workend exit event

### PR DESCRIPTION
**Pull request by studyztp**

### CODE REVIEW

**Review by powerjg — COMMENTED** [review]
Looks good! It would be good to add the tests, if you can figure it out. If you can't figure it out, then we don't have to worry about it. (I have no idea how these tests work!)

**Comment by studyztp** [comment]
> Looks good! It would be good to add the tests, if you can figure it out. If you can't figure it out, then we don't have to worry about it. (I have no idea how these tests work!)

I'll try to add them today. I only looked the tests briefly but they seem straightforward :)

**Comment by studyztp** [comment]
> Looks good! It would be good to add the tests, if you can figure it out. If you can't figure it out, then we don't have to worry about it. (I have no idea how these tests work!)

Sorry, I was looking at the test/gem5/m5_util, but this one only checks the m5op. I tried to build the test under util/m5 with the command `scons build/x86/test` but I got the `g++: error: build/x86/googletest/libgtest.a: No such file or directory` error. I looked it up a bit and still don't understand why it's missing the libgtest.a. It requires some knowledge about googletest to fix it.

**Comment by studyztp** [comment]
> Looks good! It would be good to add the tests, if you can figure it out. If you can't figure it out, then we don't have to worry about it. (I have no idea how these tests work!)

**Comment by studyztp** [comment]
Sorry, clicked the wrong button.

**Comment by powerjg** [comment]
Lol, no worries. @BobbyRBruce, are you good with submitting this to Gerrit without tests? I don't care...

**Comment by BobbyRBruce** [comment]
Nice to have tests, but I can live without them. Please push this to Gerrit!

**Comment by studyztp** [comment]
Thank you! I'll push them to Gerrit.

**Pull request closed without merging**
